### ISSUE TITLE
demo_husky_02_whole_body_control.ipynb

### ISSUE THREAD

**Issue by DevilCJS89** [joonhyung-lee/mujoco-robotics-usage#1]
when I run this code :mobile_manipulator/demo_husky_02_whole_body_control.ipynb
I have a question for 'q_ik''  is not to define ?
Thank you very much !

    # Update the simulation state
    if STEP == "MANIPULATE":
        ctrl_husky = np.zeros(4)
        ctrl_ur = q_ik
        ctrl_wholebody = ctrl_husky.tolist() + ctrl_ur.tolist()

**Comment by joonhyung-lee** [comment]
Hi! Thank you for your interest in my repository.

Here, the value of `q_ik` was a pre-defined value for the manipulator joint `qpos` to grasp the cylinder object after the mobile base reaches the target point!
`q_ik = np.array([-0.45, -0.65,  0.6 ,  1.75,  0.79, -1.57])`

This demo is still a `work-in-progress`, and I was aiming for pick-n-place automation with the mobile-manipulator. 
There are no plans to develop it yet...
