### ISSUE TITLE
TypeError: solve_ik() got an unexpected keyword argument 'rev_joint_idxs'

### ISSUE THREAD

**Issue by DevilCJS89** [joonhyung-lee/mujoco-robotics-usage#2]
demo_husky_02_whole_body_control.ipynb

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], [line 11](vscode-notebook-cell:?execution_count=9&line=11)
      [9](vscode-notebook-cell:?execution_count=9&line=9) p_trgt = env.get_p_body('obj_cylinder_01')
     [10](vscode-notebook-cell:?execution_count=9&line=10) R_trgt = env.get_R_body('obj_cylinder_01')
---> [11](vscode-notebook-cell:?execution_count=9&line=11) q_ik = env.solve_ik('obj_cylinder_01',p_trgt,R_trgt,IK_P=True,IK_R=True,q_init=init_ur_q,rev_joint_idxs=[4,5,6,7,8,9],
     [12](vscode-notebook-cell:?execution_count=9&line=12)                  RESET=False,DO_RENDER=True,render_every=1,th=1*np.pi[/](https://file+.vscode-resource.vscode-cdn.net/)180.0,err_th=1e-6)
     [14](vscode-notebook-cell:?execution_count=9&line=14) # Close viewer
     [15](vscode-notebook-cell:?execution_count=9&line=15) env.close_viewer()

TypeError: solve_ik() got an unexpected keyword argument 'rev_joint_idxs'

**Comment by joonhyung-lee** [comment]
Hi!

In the mobile manipulator system, the joint index of the mobile base and the manipulator was often mixed up. 
To avoid this, we defined a new member variable for indexing: `self.idxs_forward`, `self.idxs_jacobian`
I use the `solve_ik` function like [here](https://github.com/joonhyung-lee/mujoco-robotics-usage/blob/main/code/manipulator/demo_ur_trajectory_planning.ipynb).

```
env.init_viewer(viewer_title='UR5e with RG2 gripper',viewer_width=1200,viewer_height=800,
                viewer_hide_menus=True)
env.update_viewer(azimuth=0.0,distance=3.5,elevation=-60,lookat=[0.4,0.05,0.36],
                  VIS_TRANSPARENT=False,VIS_CONTACTPOINT=True,
                  contactwidth=0.05,contactheight=0.05,contactrgba=np.array([1,0,0,1]),
                  VIS_JOINT=True,jointlength=0.5,jointwidth=0.1,jointrgba=[0.2,0.6,0.8,0.6])
env.reset()

R_trgt = rpy2r(np.radians([-180,0,90]))

q_ik = env.solve_ik(
    body_name='tcp_link',p_trgt=np.array([1.0, -0.2, 1.10]),R_trgt=R_trgt,
    IK_P=True,IK_R=True, q_init=np.array(q_init),idxs_forward=env.idxs_forward, idxs_jacobian=env.idxs_jacobian,
    RESET=False,DO_RENDER=True,render_every=1,th=1*np.pi/180.0,err_th=1e-3,w_weight=0.3)

# Close viewer
env.close_viewer()
print ("Done.")

print(q_ik)
```

Thank you!

**Comment by DevilCJS89** [comment]
Thank you very much!
I haven't seen the code for wholebody_ik.gis of the mobile manipulator.
